export const DESIGN_PARAM_TYPES = "design:paramtypes";
export const DESIGN_TYPE = "design:type";
export const DESIGN_RETURN_TYPE = "design:returntype";
export const INJECTED_PROPERTIES = Symbol("injected properties");
export const INJECTED_ARGUMENTS = Symbol("injected arguments");
export const PROPERTIES_BOUND = Symbol("properties bound");
export const INJECTED_CLASS_TAG = Symbol("injected class tag");
export const PROPERTIES_BINDER = Symbol("properties binder");
export const SINGLE_VALUE_KEY = Symbol("single value's key");
